import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider,Container, createTheme } from '@mantine/core';
import theme from "./theme";
import { Navbar } from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mohalibes's Portfolio",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <ColorSchemeScript defaultColorScheme="dark"  />
      </head>
      <body 
      style={{ background: 'black' }}
       className="antialiased max-w-2xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto"
       >
          <MantineProvider theme={theme} defaultColorScheme="dark">
            <main  
            className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0"
            >
              <Navbar/>
            {children}
            </main>
          </MantineProvider>
      </body>
    </html>
  );
}
